mode="debug"
istioctl="/user/bin/istioctl"
namespace=""
upload_tmp="/data/www/upload_tmp/"
[logger]
    [logger.console]
        color=true
        prefix="[naftis]"
        level="Debug"
    [logger.zap]
        path="naftis-api.log"
        level="Debug"
[db]
    default="root:Aa123456@tcp(120.25.93.207:3306)/naftis?charset=utf8&parseTime=True&loc=Local" # TODO replace MySQL DSN with your own